name: docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  test:
    runs-on: ubuntu-latest
    name: Publish docs
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - run: zig build docs
      - name: setup pages
        uses: actions/configure-pages@v5
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./zig-out/docs/
      - name: deploy pages
        uses: actions/deploy-pages@v4
